const GLOBAL_TYPES = {
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  GET_PRODUCT_LINE: "GET_PRODUCT_LINE",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  SIGN_IN: "SIGN_IN",
  ERROR: "ERROR",
  DELETE_ERROR: "DELETE_ERROR",
  REFRESH_TOKEN: "REFRESH_TOKEN"
};

export default GLOBAL_TYPES;
