const GLOBAL_TYPES = {
  SIGN_IN: "SIGN_IN",
  SIGN_UP: "SIGN_UP",
  GET_PRODUCT_LINE: "GET_PRODUCT_LINE",
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID"
};

export default GLOBAL_TYPES;
